name: PHPUnit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          XDEBUG_MODE: coverage
          TEST_NAME: Scarlett
        with:
          php_extensions: xdebug
          memory_limit: 256M
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text

